### ISSUE TITLE
Write order

### ISSUE THREAD

**Issue by splitice** [longshine/Mina.NET#20]
I searched the documentation and could not find any notes on the order of write operations.

Is the order of an Asynchronous Write guaranteed? Or would an Await() be needed after each to guarantee order?

**Comment by longshine** [comment]
Hi~

The order **is** guaranteed by a `IWriteRequestQueue` inside each session. Write operations will be wrapped into `IWriteRequest`s and be queued before being actually sent. The `MessageSent` event will also be fired one by one in the same order.

You don't have to call `Await()` unless you want to receive some responses from the remote :)

I'll improve the docs later. Thanks for ask.

**Comment by splitice** [comment]
Thank you :)
