### ISSUE TITLE
接收数据异常

### ISSUE THREAD

**Issue by oojeek** [longshine/Mina.NET#22]
程序正在接收大量数据时，如果突然断开网络，AsyncSocketSession.NET20.cs中BeginSend中的Socket.BeginSend(array.Array, array.Offset, array.Count, SocketFlags.None, SendCallback, new SendingContext(Socket, buf)); 方法会抛出SocketException异常，导致程序崩溃

**Comment by longshine** [comment]
Thank u. Fixed in 37073cebaa961db2e5dc42337f699ee85cbc47b0. (ref #25)
